export const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

export type TRANSACTION_STATUS = keyof typeof TRANSACTION_STATUS;

export const TRANSACTION_TYPE = {
  TOP_UP: 'TOP_UP',
  CAMPAIGN_DEBIT: 'CAMPAIGN_DEBIT',
  REFUND: 'REFUND',
};

export type TRANSACTION_TYPE = keyof typeof TRANSACTION_TYPE;
